/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication18;

/**
 *
 * @author ideaPad
 */
public class minimize extends javax.swing.JFrame {

    /**
     * Creates new form minimize
     */
    public minimize() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valid = new javax.swing.JTextField();
        starting = new javax.swing.JTextField();
        finalstate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        allstates = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        transition = new javax.swing.JTextField();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        valid.setBackground(new java.awt.Color(125, 104, 104));
        valid.setForeground(new java.awt.Color(255, 255, 255));
        valid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        getContentPane().add(valid);
        valid.setBounds(520, 240, 500, 70);

        starting.setBackground(new java.awt.Color(125, 104, 104));
        starting.setForeground(new java.awt.Color(255, 255, 255));
        starting.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(starting);
        starting.setBounds(621, 342, 490, 70);

        finalstate.setBackground(new java.awt.Color(125, 104, 104));
        finalstate.setForeground(new java.awt.Color(255, 255, 255));
        finalstate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(finalstate);
        finalstate.setBounds(521, 442, 490, 70);

        jButton1.setBackground(new java.awt.Color(249, 255, 98));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(945, 653, 160, 60);

        allstates.setBackground(new java.awt.Color(125, 104, 104));
        allstates.setForeground(new java.awt.Color(255, 255, 255));
        allstates.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(allstates);
        allstates.setBounds(481, 542, 510, 70);

        jButton2.setBackground(new java.awt.Color(249, 255, 98));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jButton2.setText("Back");
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 120, 60);

        transition.setBackground(new java.awt.Color(125, 104, 104));
        transition.setForeground(new java.awt.Color(255, 255, 255));
        transition.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(transition);
        transition.setBounds(430, 630, 500, 80);

        back.setBackground(new java.awt.Color(125, 104, 104));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication18/mini.png"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(-3, -4, 1440, 1024);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new minimize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allstates;
    private javax.swing.JLabel back;
    private javax.swing.JTextField finalstate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField starting;
    private javax.swing.JTextField transition;
    private javax.swing.JTextField valid;
    // End of variables declaration//GEN-END:variables
}
